// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EmotionsController from "./emotions_controller"
application.register("emotions", EmotionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
