version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
     - "./data/redis:/data"
volumes:
  db-store:
